// Generated by CoffeeScript 1.6.3
// jQuery(function() {
//   return $.each($("[data-time]"), function(index, ele) {
//     return $(ele).html(prettyDate(new Date($(this).data("time"))));
//   });
// });
jQuery(function() {
  $.each($('.project-container'), function(index, element) {
    $(element).click(function() {
      var popover = $(element).find('.project-description');
      popover.toggleClass('hidden');

      if (popover.hasClass('hidden')) {
        $(element).parent().css('margin-bottom', '20px');
        $(element).find('.project-hover').removeClass('active');
      } else {
        $(element).parent().css('margin-bottom', 20 + popover.height() + 2 * parseInt(popover.css('margin-top')));
        $(element).find('.project-hover').addClass('active');

      }
    });

    $(element).mouseenter(function() {
      if ($(element).find('.project-description').hasClass('hidden')) {
        $(element).find('.project-hover').addClass('active');
      }
    });

    $(element).mouseleave(function() {
      if ($(element).find('.project-description').hasClass('hidden')) {
        $(element).find('.project-hover').removeClass('active');
      }
    });
  });
});
