// Generated by CoffeeScript 1.6.3
// jQuery(function() {
//   return $.each($("[data-time]"), function(index, ele) {
//     return $(ele).html(prettyDate(new Date($(this).data("time"))));
//   });
// });
jQuery(function() {
  $.each($('.project-container'), function(index, element) {
    $(element).click(function() {
      var popover = $(element).find('.project-description');
      popover.toggleClass('hidden');

      if (popover.hasClass('hidden')) {
        $(element).css('margin-bottom', 0);
      } else {
        $(element).css('margin-bottom', popover.height() + 2 * parseInt(popover.css('margin-top')));
      }
    });

    $(element).hover(function() {
      $(element).find('.project-hover').toggleClass('active');
    })
  });
});
